db/init.sql, src/lib/server/database.ts, src/lib/server/model/session.ts
This PR introduces department level abstractions in the database and made the necessary changes to other tables' schemas.
- Removed the `agents` table (deemed unnecessary as we can assign users to a department first, thereby distinguishing them as agents) and introduces `admin` field in `users` table (which was originally in the `agents` table schema).
- Created the `depts` table for the departments.
- Created the `dept_agents` table which indicates the agents assigned to each department with an additional field `head` that distinguishes a certain agent as a department head. (not to be confused with the `admin` or system admin as indicated in the `users` table.)
- Created the `dept_labels` table which indicates the labels that can be handled by each department as determined by the …
=> feat(db): introduce department level abstractions to database

db/init.sql, src/api/label.ts, src/lib/model/label.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/label/deadline/+server.ts
This adds a new nullable `deadline` property for the `labels` table, which basically stores the default deadline (as a number of days) for any ticket that has been created with a label. A `NULL` deadline simply means "no deadline" (i.e., unlimited number of days). For example, suppose a label with a default deadline of five days. Then, any ticket that is created with the label assigned to it must have a due date that is set five days from now.
As such, we must modify the original `POST /api/label` endpoint to account for the new `deadline` field. We also add a new endpoint `PATCH /api/label/deadline` for setting the `deadline` to some number of days or `null`.
=> feat(api): implement per-label deadlines

db/init.sql, src/api/user.ts, src/lib/model/user.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/user/admin/+server.ts
Requires #6 to be merged first.
This PR implements the endpoint `PATCH /api/user/admin`, which promotes/demotes a system administrator by their `user_id`.
=> feat(api): system administrator promotion/demotion

src/lib/api/dept.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/dept/name/+server.ts
This PR introduces the endpoint for editing the `name` of a `Dept` or department via `PATCH /api/dept/name`.
=> feat(api): implement department renaming

db/init.sql, src/lib/model/agent.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/dept/+server.ts, src/routes/api/dept/name/+server.ts, src/routes/api/label/+server.ts, src/routes/api/label/color/+server.ts, src/routes/api/label/deadline/+server.ts, src/routes/api/label/title/+server.ts, src/routes/api/user/admin/+server.ts
This PR implements department-level and system-level permission checks. This required me to remove the `dept_agents.dept_agent_id` field in favor of the composite primary key `(dept_id, user_id)`. In line with the more granular checks, I have also refactored the endpoints to use the new helper functions.
=> feat(db): implement more granular permission checks

db/init.sql, src/lib/api/dept.ts, src/lib/api/label.ts, src/lib/api/priority.ts, src/lib/api/user.ts, src/lib/model/priority.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/priority/+server.ts
Requires #10 to be merged.
This PR implements the `POST /api/priority` endpoint, which creates a single entry in the `priorities` table. In the future, this allows user to assign a priority to a ticket with an associated "title" and "priority level". In the far future, this lets us sort an inbox by priority.
=> feat(api): implement priority creation

db/init.sql, src/lib/api/ticket.ts, src/lib/model/ticket.ts, src/lib/server/database/error.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/ticket/+server.ts
This PR implements the ticket creation API: `POST /api/ticket`. It accepts the following arguments as a `application/x-www-urlencoded` request body:
* The `title` of the ticket.
* The `content` of the first message in the thread.
* Zero or more `label` IDs which automatically triage the ticket.
=> feat(api): implement ticket creation

db/init.sql, src/lib/api/dept.ts, src/lib/model/dept.ts, src/lib/server/database/error.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/dept/label/+server.ts
This PR implements the new endpoint `POST /api/dept/label`, which subscribes a `Dept` to a subset of the available system `Label`s (as added by `POST /api/label`). In an actual form, the user creates a new ticket by indicating its "category". The labels that will be shown in the dropdown menu will be determined by the labels that a department _does_ subscribe to.
When the ticket is created, all subscribed departments are automatically assigned to the ticket. Any agent from the respective departments may now volunteer the assignment or be assigned to the ticket by some department head.
=> feat(api): opting in to department-specific label subscriptions

db/init.sql, src/lib/api/ticket.ts, src/lib/model/ticket.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/ticket/+server.ts, src/routes/api/ticket/reply/+server.ts, src/routes/auth/callback/+server.ts
This PR adds a new endpoint `POST /api/ticket/reply`, which submits a new reply to an existing ticket.
=> feat(api): implement reply creation

db/init.sql, src/lib/api/ticket.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/ticket/title/+server.ts
This PR implements editing the `title` field of an existing ticket.
> **Warning**
> The current implementation does not do any permission checks. Ideally, editing the ticket title should only be allowed for the ticket author and assigned agents.
=> feat(api): implement editing of ticket title

db/init.sql, src/lib/api/agent.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/agent/+server.ts
This PR introduces the `DELETE /api/agent` endpoint that removes a specified agent from the specified department.
> NOTE: (as far as I know) The DELETE statement does not throw an error when one of the input values is non-existent in the table but simply returns that it has affected zero rows, thus making the current way of checking for incorrect `dept_id` or `user_id` values inapplicable to this situation.
=> feat(api): implement removal of department agents

src/lib/api/ticket.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/ticket/priority/+server.ts
This PR implements the assignment of the priority of a ticket via the `priority_id` field, done by an assigned agent.
Also introduces `AssignTicketPriorityResult` for handling cases where the provided priority does not exist.
=> feat(api): implement assignment of priority to a ticket

db/init.sql, src/lib/api/ticket.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/ticket/label/+server.ts
This PR implements `POST /api/ticket/label`, which assigns a label to a ticket one by one. It requires that the user is an assigned agent to the ticket.
Moreover, this PR also fixes a bug with `POST /api/agent`, which doesn't actually return the `Exists` variant prior to my changes.
=> feat(api): implement ticket label assignment

db/init.sql, src/lib/api/ticket.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/ticket/reply/+server.ts, src/routes/api/ticket/status/+server.ts, src/routes/api/ticket/title/+server.ts
This PR introduces an endpoint `PATCH /api/ticket/status` which allows the ticket author or assigned agents to edit the status of ticket from Open to Closed/Resolved or vice-versa. The endpoint returns the previous status of the ticket.
=> feat(api): implement ticket status changing

db/funcs.sql, src/lib/model/label.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts
Made getters for Agents, Departments, Dept Labels, Labels, Messages, Pendings, Prioties, Tickets, Ticket Labels, and Users
Added get_agents_by_dept  and users_outside_dept to func.sql
Made generic test cases for all getters (expect to be greater than 0)
=> feat (api): Implemented getters

db/funcs.sql, src/lib/api/ticket.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/api/ticket/claim/+server.ts
This PR implements the ability for agents to "self-assign" or "claim" a ticket. The only requirement to invoke the endpoint `POST /api/ticket/claim` is that the agent must already be a member of the department that _is_ subscribed to a label previously assigned to that ticket.
=> feat(api): implement agent self-assignment

src/routes/dashboard/+layout.svelte
This PR converts the sidebar to an App Rail component provided by the Skeleton toolkit. The avatar and name were moved to the trail of the App Bar.
To implement:
Things to consider regarding the dashboard: maybe replace with an inbox to show active tickets?
=> refactor: convert sidebar to app rail (initial)

src/routes/dashboard/ticket/+page.server.ts, src/routes/dashboard/ticket/+page.svelte
This PR simplifies the ticket creation process by automatically redirecting the user straight to the newly created thread instead of showing an alert message.
- This should actually apply for all of the `<form>` elements.
=> refactor(ui): redirect the user on ticket creation

db/funcs.sql, db/tables.sql, package.json, pnpm-lock.yaml, src/lib/model/ticket.ts, src/lib/server/database/index.test.ts, src/lib/server/database/index.ts, src/routes/dashboard/inbox/Inbox.svelte, src/routes/dashboard/ticket/+page.server.ts, src/routes/dashboard/ticket/[id]/+page.server.ts, src/routes/dashboard/ticket/[id]/+page.svelte
This PR sorts the inbox by their priority level (descending with `null` last), then by their due date (ascending), and finally by their creation date (ascending). Note that untriaged tickets are sorted last.
To simplify the queries involved, I removed the `messages.message_id` field in favor of the `messages.creation` field. That is to say, the `creation` field is now the new primary key for the `messages` table. The timestamp (with time zone) should be sufficiently unique for most cases. In the worst (but incredibly exceptional) case when a timestamp collision occurs, the user simply retries the operation.
=> feat: order inbox by priority => due date => creation

LICENSE
This PR finally adds the AGPL v3 license to the project. This is a strong copyleft license which (1) requires redistributions to maintain our copyright, (2) requires modifications to be published open-source as well, and (3) protects us from liability among many other stipulations and legal ramifications. Please review the the full legal text or at least any of the resources below.
> [!NOTE]
> I am of course open to alternate licenses—simply make your case in the comments below.
* [TLDR Legal](https://www.tldrlegal.com/license/gnu-affero-general-public-license-v3-agpl-3-0)
* [Why the GNU Affero GPL](https://www.gnu.org/licenses/why-affero-gpl.html)
* [The fundamentals of the AGPLv3](https://www.fsf.org/bulletin/2021/fall/the-fundamentals-of-the-agplv3)
* [Open Source Software Licenses …
=> chore: add project license
